// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_iconWeather
void ui_iconWeather_screen_init(void);
lv_obj_t * ui_iconWeather;
lv_obj_t * ui_Background;
lv_obj_t * ui_bg1;
lv_obj_t * ui_IconWeather;
lv_obj_t * ui_LogoDsoft;
lv_obj_t * ui_Hi;
lv_obj_t * ui_Welcome;
lv_obj_t * ui_OnOff1;
lv_obj_t * ui_OnOff2;
lv_obj_t * ui_AQI;
lv_obj_t * ui_LogoAQI;
lv_obj_t * ui_Good;
lv_obj_t * ui_Image56;
lv_obj_t * ui_Image60;
lv_obj_t * ui_Image61;
lv_obj_t * ui_ChartDust;
lv_obj_t * ui_ChartNoise;
lv_obj_t * ui_Co2;
lv_obj_t * ui_Dust1;
lv_obj_t * ui_ChartTemp;
lv_obj_t * ui_ChartHumidity;
lv_obj_t * ui_CO;
lv_obj_t * ui_IconCO;
lv_obj_t * ui_Image55;
lv_obj_t * ui_Image74;
lv_obj_t * ui_Image75;
lv_obj_t * ui_Image76;
lv_obj_t * ui_Image77;
lv_obj_t * ui_IconPM25;
lv_obj_t * ui_Image79;
lv_obj_t * ui_Image80;
lv_obj_t * ui_IconTemp;
lv_obj_t * ui_TVOCs;
lv_obj_t * ui_IconHumidity;
lv_obj_t * ui_Humidity;
lv_obj_t * ui_IconPM10;
lv_obj_t * ui_PM10;
lv_obj_t * ui_CH4;
lv_obj_t * ui_IconCH4;
lv_obj_t * ui_NH3;
lv_obj_t * ui_IconNH3;
lv_obj_t * ui_IAQ;
lv_obj_t * ui_IconTVOCs;
lv_obj_t * ui_PM25;
lv_obj_t * ui_DvDust;
lv_obj_t * ui_IconIAQ;
lv_obj_t * ui_Temp;
lv_obj_t * ui_IconCO2;
lv_obj_t * ui_Noise;
lv_obj_t * ui_DvNoise;
lv_obj_t * ui_Switch2;
lv_obj_t * ui_Switch1;
lv_obj_t * ui_Image3;
lv_obj_t * ui_SmartLarm2;
lv_obj_t * ui_Room2;
lv_obj_t * ui_Image6;
lv_obj_t * ui_Image7;
lv_obj_t * ui_SmartLarm1;
lv_obj_t * ui_Room1;
lv_obj_t * ui_Image10;
lv_obj_t * ui_Image13;
lv_obj_t * ui_Image14;
lv_obj_t * ui_Delivery;
lv_obj_t * ui_AIoT;
lv_obj_t * ui_NumCo2;
lv_obj_t * ui_NumPM25;
lv_obj_t * ui_NumCO;
lv_obj_t * ui_NumTVOCs;
lv_obj_t * ui_NumPM10;
lv_obj_t * ui_NumCH4;
lv_obj_t * ui_NumNH3;
lv_obj_t * ui_NumIAQ;
lv_obj_t * ui_NumAQI;
lv_obj_t * ui_NumTemp;
lv_obj_t * ui_NumHumdity;
lv_obj_t * ui_Num;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_[12] = {&ui_img_1_png, &ui_img_11_png, &ui_img_11111_png, &ui_img_2222_png, &ui_img_3_png, &ui_img_25_png, &ui_img_34_png, &ui_img_44_png, &ui_img_45_png, &ui_img_54_png, &ui_img_66_png, &ui_img_777_png};
const lv_img_dsc_t * ui_imgset__00[3] = {&ui_img_12_00_png, &ui_img_15_00_png, &ui_img_42_00_png};
const lv_img_dsc_t * ui_imgset__74[1] = {&ui_img_30_74_png};
const lv_img_dsc_t * ui_imgset_119175153[1] = {&ui_img_1027177112};
const lv_img_dsc_t * ui_imgset__45[1] = {&ui_img_500_45_png};
const lv_img_dsc_t * ui_imgset__30[1] = {&ui_img_8_30_png};
const lv_img_dsc_t * ui_imgset__55[1] = {&ui_img_90_55_png};
const lv_img_dsc_t * ui_imgset_bg_light_[1] = {&ui_img_bg_light_1_png};
const lv_img_dsc_t * ui_imgset_bg_light[1] = {&ui_img_bg_light2_png};
const lv_img_dsc_t * ui_imgset_ch[1] = {&ui_img_ch4_png};
const lv_img_dsc_t * ui_imgset_co[1] = {&ui_img_co2_png};
const lv_img_dsc_t * ui_imgset_ellipse_[1] = {&ui_img_ellipse_338_png};
const lv_img_dsc_t * ui_imgset_frame_[16] = {&ui_img_frame_1_png, &ui_img_frame_11_png, &ui_img_frame_2_png, &ui_img_frame_13_png, &ui_img_frame_3_png, &ui_img_frame_14_png, &ui_img_frame_5_png, &ui_img_frame_6_png, &ui_img_frame_17_png, &ui_img_frame_18_png, &ui_img_frame_32_png, &ui_img_frame_36_png, &ui_img_frame_41_png, &ui_img_frame_43_png, &ui_img_frame_46_png, &ui_img_frame_53_png};
const lv_img_dsc_t * ui_imgset_group_[2] = {&ui_img_group_2_png, &ui_img_group_4_png};
const lv_img_dsc_t * ui_imgset_layer_[1] = {&ui_img_layer_1_png};
const lv_img_dsc_t * ui_imgset_nh[1] = {&ui_img_nh3_png};
const lv_img_dsc_t * ui_imgset_pm[1] = {&ui_img_pm10_png};
const lv_img_dsc_t * ui_imgset_pm_5[1] = {&ui_img_pm2_5_png};
const lv_img_dsc_t * ui_imgset_1114065945[1] = {&ui_img_320661724};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 32
    #error "LV_COLOR_DEPTH should be 32bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_iconWeather_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_iconWeather);
}
