// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_iconWeather
void ui_iconWeather_screen_init(void);
extern lv_obj_t * ui_iconWeather;
extern lv_obj_t * ui_Background;
extern lv_obj_t * ui_bg1;
extern lv_obj_t * ui_IconWeather;
extern lv_obj_t * ui_LogoDsoft;
extern lv_obj_t * ui_Hi;
extern lv_obj_t * ui_Welcome;
extern lv_obj_t * ui_OnOff1;
extern lv_obj_t * ui_OnOff2;
extern lv_obj_t * ui_AQI;
extern lv_obj_t * ui_LogoAQI;
extern lv_obj_t * ui_Good;
extern lv_obj_t * ui_Image56;
extern lv_obj_t * ui_Image60;
extern lv_obj_t * ui_Image61;
extern lv_obj_t * ui_ChartDust;
extern lv_obj_t * ui_ChartNoise;
extern lv_obj_t * ui_Co2;
extern lv_obj_t * ui_Dust1;
extern lv_obj_t * ui_ChartTemp;
extern lv_obj_t * ui_ChartHumidity;
extern lv_obj_t * ui_CO;
extern lv_obj_t * ui_IconCO;
extern lv_obj_t * ui_Image55;
extern lv_obj_t * ui_Image74;
extern lv_obj_t * ui_Image75;
extern lv_obj_t * ui_Image76;
extern lv_obj_t * ui_Image77;
extern lv_obj_t * ui_IconPM25;
extern lv_obj_t * ui_Image79;
extern lv_obj_t * ui_Image80;
extern lv_obj_t * ui_IconTemp;
extern lv_obj_t * ui_TVOCs;
extern lv_obj_t * ui_IconHumidity;
extern lv_obj_t * ui_Humidity;
extern lv_obj_t * ui_IconPM10;
extern lv_obj_t * ui_PM10;
extern lv_obj_t * ui_CH4;
extern lv_obj_t * ui_IconCH4;
extern lv_obj_t * ui_NH3;
extern lv_obj_t * ui_IconNH3;
extern lv_obj_t * ui_IAQ;
extern lv_obj_t * ui_IconTVOCs;
extern lv_obj_t * ui_PM25;
extern lv_obj_t * ui_DvDust;
extern lv_obj_t * ui_IconIAQ;
extern lv_obj_t * ui_Temp;
extern lv_obj_t * ui_IconCO2;
extern lv_obj_t * ui_Noise;
extern lv_obj_t * ui_DvNoise;
extern lv_obj_t * ui_Switch2;
extern lv_obj_t * ui_Switch1;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_SmartLarm2;
extern lv_obj_t * ui_Room2;
extern lv_obj_t * ui_Image6;
extern lv_obj_t * ui_Image7;
extern lv_obj_t * ui_SmartLarm1;
extern lv_obj_t * ui_Room1;
extern lv_obj_t * ui_Image10;
extern lv_obj_t * ui_Image13;
extern lv_obj_t * ui_Image14;
extern lv_obj_t * ui_Delivery;
extern lv_obj_t * ui_AIoT;
extern lv_obj_t * ui_NumCo2;
extern lv_obj_t * ui_NumPM25;
extern lv_obj_t * ui_NumCO;
extern lv_obj_t * ui_NumTVOCs;
extern lv_obj_t * ui_NumPM10;
extern lv_obj_t * ui_NumCH4;
extern lv_obj_t * ui_NumNH3;
extern lv_obj_t * ui_NumIAQ;
extern lv_obj_t * ui_NumAQI;
extern lv_obj_t * ui_NumTemp;
extern lv_obj_t * ui_NumHumdity;
extern lv_obj_t * ui_Num;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_background_png);    // assets\Background.png
LV_IMG_DECLARE(ui_img_3_png);    // assets\3.png
LV_IMG_DECLARE(ui_img_1027177112);    // assets\3d-render-weather-icons-set-sun-clouds-crescent 1.png
LV_IMG_DECLARE(ui_img_2131548591);    // assets\logo-D-soft.png
LV_IMG_DECLARE(ui_img_571830898);    // assets\Hi, have a good date!.png
LV_IMG_DECLARE(ui_img_842616905);    // assets\Welcome to IOT Department! The air quality is good & fresh.png
LV_IMG_DECLARE(ui_img_on_png);    // assets\On.png
LV_IMG_DECLARE(ui_img_air_quality_index_png);    // assets\Air Quality Index.png
LV_IMG_DECLARE(ui_img_icon_circle_index_png);    // assets\icon_circle_index.png
LV_IMG_DECLARE(ui_img_668426069);    // assets\Frame 17 (1).png
LV_IMG_DECLARE(ui_img_frame_43_png);    // assets\Frame 43.png
LV_IMG_DECLARE(ui_img_frame_36_png);    // assets\Frame 36.png
LV_IMG_DECLARE(ui_img_co2_png);    // assets\CO2.png
LV_IMG_DECLARE(ui_img_dust_png);    // assets\Dust.png
LV_IMG_DECLARE(ui_img_group_4_png);    // assets\Group 4.png
LV_IMG_DECLARE(ui_img_co_png);    // assets\CO.png
LV_IMG_DECLARE(ui_img_1302822862);    // assets\ic_round-volume-up.png
LV_IMG_DECLARE(ui_img_vector_png);    // assets\Vector.png
LV_IMG_DECLARE(ui_img_1490288613);    // assets\Frame 13 (3).png
LV_IMG_DECLARE(ui_img_960377382);    // assets\mingcute_snow-fill.png
LV_IMG_DECLARE(ui_img_tvocs_png);    // assets\TVOCs.png
LV_IMG_DECLARE(ui_img_1_png);    // assets\1.png
LV_IMG_DECLARE(ui_img_humidity_png);    // assets\Humidity.png
LV_IMG_DECLARE(ui_img_pm10_png);    // assets\PM10.png
LV_IMG_DECLARE(ui_img_ch4_png);    // assets\CH4.png
LV_IMG_DECLARE(ui_img_320661724);    // assets\Screenshot 2024-06-20 at 10.50.46 1.png
LV_IMG_DECLARE(ui_img_nh3_png);    // assets\NH3.png
LV_IMG_DECLARE(ui_img_777_png);    // assets\777.png
LV_IMG_DECLARE(ui_img_iaq_png);    // assets\IAQ.png
LV_IMG_DECLARE(ui_img_66_png);    // assets\66.png
LV_IMG_DECLARE(ui_img_pm2_5_png);    // assets\PM2.5.png
LV_IMG_DECLARE(ui_img_433014539);    // assets\m³).png
LV_IMG_DECLARE(ui_img_194552828);    // assets\fill (2).png
LV_IMG_DECLARE(ui_img_temp_png);    // assets\Temp.png
LV_IMG_DECLARE(ui_img_2222_png);    // assets\2222.png
LV_IMG_DECLARE(ui_img_44_png);    // assets\44.png
LV_IMG_DECLARE(ui_img_247956599);    // assets\(dB).png
LV_IMG_DECLARE(ui_img_1902665014);    // assets\lamp-on.png
LV_IMG_DECLARE(ui_img_1078347737);    // assets\Smart Larm (1).png
LV_IMG_DECLARE(ui_img_mr_water_png);    // assets\Mr.Water.png
LV_IMG_DECLARE(ui_img_54_png);    // assets\54.png
LV_IMG_DECLARE(ui_img_45_png);    // assets\45.png
LV_IMG_DECLARE(ui_img_11_png);    // assets\11.png
LV_IMG_DECLARE(ui_img_delivery_department_png);    // assets\Delivery Department.png
LV_IMG_DECLARE(ui_img_aiot_department_png);    // assets\AIoT Department.png
LV_IMG_DECLARE(ui_img_11111_png);    // assets\11111.png
LV_IMG_DECLARE(ui_img_12_00_png);    // assets\12.00.png
LV_IMG_DECLARE(ui_img_15_00_png);    // assets\15.00.png
LV_IMG_DECLARE(ui_img_25_png);    // assets\25.png
LV_IMG_DECLARE(ui_img_30_74_png);    // assets\30.74.png
LV_IMG_DECLARE(ui_img_34_png);    // assets\34.png
LV_IMG_DECLARE(ui_img_42_00_png);    // assets\42.00.png
LV_IMG_DECLARE(ui_img_500_45_png);    // assets\500.45.png
LV_IMG_DECLARE(ui_img_8_30_png);    // assets\8.30.png
LV_IMG_DECLARE(ui_img_90_55_png);    // assets\90.55.png
LV_IMG_DECLARE(ui_img_bg_light_1_png);    // assets\Bg_Light 1.png
LV_IMG_DECLARE(ui_img_bg_light2_png);    // assets\Bg_light2.png
LV_IMG_DECLARE(ui_img_ellipse_338_png);    // assets\Ellipse 338.png
LV_IMG_DECLARE(ui_img_frame_1_png);    // assets\Frame 1.png
LV_IMG_DECLARE(ui_img_frame_11_png);    // assets\Frame 11.png
LV_IMG_DECLARE(ui_img_frame_13_png);    // assets\Frame 13.png
LV_IMG_DECLARE(ui_img_frame_14_png);    // assets\Frame 14.png
LV_IMG_DECLARE(ui_img_frame_17_png);    // assets\Frame 17.png
LV_IMG_DECLARE(ui_img_frame_18_png);    // assets\Frame 18.png
LV_IMG_DECLARE(ui_img_frame_2_png);    // assets\Frame 2.png
LV_IMG_DECLARE(ui_img_frame_3_png);    // assets\Frame 3.png
LV_IMG_DECLARE(ui_img_frame_32_png);    // assets\Frame 32.png
LV_IMG_DECLARE(ui_img_frame_41_png);    // assets\Frame 41.png
LV_IMG_DECLARE(ui_img_frame_46_png);    // assets\Frame 46.png
LV_IMG_DECLARE(ui_img_frame_5_png);    // assets\Frame 5.png
LV_IMG_DECLARE(ui_img_frame_53_png);    // assets\Frame 53.png
LV_IMG_DECLARE(ui_img_frame_6_png);    // assets\Frame 6.png
LV_IMG_DECLARE(ui_img_group_2_png);    // assets\Group 2.png
LV_IMG_DECLARE(ui_img_layer_1_png);    // assets\Layer_1.png



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
