// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_iconWeather_screen_init(void)
{
    ui_iconWeather = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_iconWeather, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Background = lv_img_create(ui_iconWeather);
    lv_img_set_src(ui_Background, &ui_img_background_png);
    lv_obj_set_width(ui_Background, LV_SIZE_CONTENT);   /// 1024
    lv_obj_set_height(ui_Background, LV_SIZE_CONTENT);    /// 600
    lv_obj_set_align(ui_Background, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Background, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Background, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_bg1 = lv_img_create(ui_iconWeather);
    lv_img_set_src(ui_bg1, &ui_img_3_png);
    lv_obj_set_width(ui_bg1, LV_SIZE_CONTENT);   /// 1024
    lv_obj_set_height(ui_bg1, LV_SIZE_CONTENT);    /// 600
    lv_obj_set_x(ui_bg1, 3);
    lv_obj_set_y(ui_bg1, 30);
    lv_obj_set_align(ui_bg1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_bg1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_bg1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_IconWeather = lv_img_create(ui_iconWeather);
    lv_img_set_src(ui_IconWeather, &ui_img_1027177112);
    lv_obj_set_width(ui_IconWeather, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_IconWeather, LV_SIZE_CONTENT);    /// 62
    lv_obj_set_x(ui_IconWeather, -265);
    lv_obj_set_y(ui_IconWeather, -109);
    lv_obj_set_align(ui_IconWeather, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_IconWeather, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_IconWeather, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LogoDsoft = lv_img_create(ui_iconWeather);
    lv_img_set_src(ui_LogoDsoft, &ui_img_2131548591);
    lv_obj_set_width(ui_LogoDsoft, LV_SIZE_CONTENT);   /// 130
    lv_obj_set_height(ui_LogoDsoft, LV_SIZE_CONTENT);    /// 37
    lv_obj_set_x(ui_LogoDsoft, -412);
    lv_obj_set_y(ui_LogoDsoft, -261);
    lv_obj_set_align(ui_LogoDsoft, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_LogoDsoft, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_LogoDsoft, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Hi = lv_img_create(ui_iconWeather);
    lv_img_set_src(ui_Hi, &ui_img_571830898);
    lv_obj_set_width(ui_Hi, LV_SIZE_CONTENT);   /// 207
    lv_obj_set_height(ui_Hi, LV_SIZE_CONTENT);    /// 21
    lv_obj_set_x(ui_Hi, -356);
    lv_obj_set_y(ui_Hi, -194);
    lv_obj_set_align(ui_Hi, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Hi, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Hi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Welcome = lv_img_create(ui_iconWeather);
    lv_img_set_src(ui_Welcome, &ui_img_842616905);
    lv_obj_set_width(ui_Welcome, LV_SIZE_CONTENT);   /// 172
    lv_obj_set_height(ui_Welcome, LV_SIZE_CONTENT);    /// 28
    lv_obj_set_x(ui_Welcome, -375);
    lv_obj_set_y(ui_Welcome, -151);
    lv_obj_set_align(ui_Welcome, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Welcome, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Welcome, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_OnOff1 = lv_img_create(ui_iconWeather);
    lv_img_set_src(ui_OnOff1, &ui_img_on_png);
    lv_obj_set_width(ui_OnOff1, LV_SIZE_CONTENT);   /// 16
    lv_obj_set_height(ui_OnOff1, LV_SIZE_CONTENT);    /// 9
    lv_obj_set_x(ui_OnOff1, -453);
    lv_obj_set_y(ui_OnOff1, 75);
    lv_obj_set_align(ui_OnOff1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_OnOff1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_OnOff1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_OnOff2 = lv_img_create(ui_iconWeather);
    lv_img_set_src(ui_OnOff2, &ui_img_on_png);
    lv_obj_set_width(ui_OnOff2, LV_SIZE_CONTENT);   /// 16
    lv_obj_set_height(ui_OnOff2, LV_SIZE_CONTENT);    /// 9
    lv_obj_set_x(ui_OnOff2, -319);
    lv_obj_set_y(ui_OnOff2, 75);
    lv_obj_set_align(ui_OnOff2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_OnOff2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_OnOff2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AQI = lv_img_create(ui_iconWeather);
    lv_img_set_src(ui_AQI, &ui_img_air_quality_index_png);
    lv_obj_set_width(ui_AQI, LV_SIZE_CONTENT);   /// 112
    lv_obj_set_height(ui_AQI, LV_SIZE_CONTENT);    /// 16
    lv_obj_set_x(ui_AQI, -42);
    lv_obj_set_y(ui_AQI, -197);
    lv_obj_set_align(ui_AQI, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AQI, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_AQI, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LogoAQI = lv_img_create(ui_iconWeather);
    lv_img_set_src(ui_LogoAQI, &ui_img_icon_circle_index_png);
    lv_obj_set_width(ui_LogoAQI, LV_SIZE_CONTENT);   /// 205
    lv_obj_set_height(ui_LogoAQI, LV_SIZE_CONTENT);    /// 186
    lv_obj_set_x(ui_LogoAQI, -78);
    lv_obj_set_y(ui_LogoAQI, -42);
    lv_obj_set_align(ui_LogoAQI, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_LogoAQI, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_LogoAQI, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Good = lv_img_create(ui_iconWeather);
    lv_img_set_src(ui_Good, &ui_img_668426069);
    lv_obj_set_width(ui_Good, LV_SIZE_CONTENT);   /// 41
    lv_obj_set_height(ui_Good, LV_SIZE_CONTENT);    /// 19
    lv_obj_set_x(ui_Good, -80);
    lv_obj_set_y(ui_Good, -1);
    lv_obj_set_align(ui_Good, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Good, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Good, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image56 = lv_img_create(ui_iconWeather);
    lv_img_set_src(ui_Image56, &ui_img_frame_43_png);
    lv_obj_set_width(ui_Image56, LV_SIZE_CONTENT);   /// 118
    lv_obj_set_height(ui_Image56, LV_SIZE_CONTENT);    /// 127
    lv_obj_set_x(ui_Image56, 451);
    lv_obj_set_y(ui_Image56, 29);
    lv_obj_set_align(ui_Image56, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image56, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image56, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image60 = lv_img_create(ui_iconWeather);
    lv_img_set_src(ui_Image60, &ui_img_frame_43_png);
    lv_obj_set_width(ui_Image60, LV_SIZE_CONTENT);   /// 118
    lv_obj_set_height(ui_Image60, LV_SIZE_CONTENT);    /// 127
    lv_obj_set_x(ui_Image60, 353);
    lv_obj_set_y(ui_Image60, 29);
    lv_obj_set_align(ui_Image60, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image60, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image60, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image61 = lv_img_create(ui_iconWeather);
    lv_img_set_src(ui_Image61, &ui_img_frame_43_png);
    lv_obj_set_width(ui_Image61, LV_SIZE_CONTENT);   /// 118
    lv_obj_set_height(ui_Image61, LV_SIZE_CONTENT);    /// 127
    lv_obj_set_x(ui_Image61, 251);
    lv_obj_set_y(ui_Image61, 33);
    lv_obj_set_align(ui_Image61, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image61, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image61, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ChartDust = lv_img_create(ui_iconWeather);
    lv_img_set_src(ui_ChartDust, &ui_img_frame_36_png);
    lv_obj_set_width(ui_ChartDust, LV_SIZE_CONTENT);   /// 227
    lv_obj_set_height(ui_ChartDust, LV_SIZE_CONTENT);    /// 103
    lv_obj_set_x(ui_ChartDust, -351);
    lv_obj_set_y(ui_ChartDust, 216);
    lv_obj_set_align(ui_ChartDust, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ChartDust, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ChartDust, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ChartNoise = lv_img_create(ui_iconWeather);
    lv_img_set_src(ui_ChartNoise, &ui_img_frame_36_png);
    lv_obj_set_width(ui_ChartNoise, LV_SIZE_CONTENT);   /// 227
    lv_obj_set_height(ui_ChartNoise, LV_SIZE_CONTENT);    /// 103
    lv_obj_set_x(ui_ChartNoise, -79);
    lv_obj_set_y(ui_ChartNoise, 219);
    lv_obj_set_align(ui_ChartNoise, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ChartNoise, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ChartNoise, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Co2 = lv_img_create(ui_iconWeather);
    lv_img_set_src(ui_Co2, &ui_img_co2_png);
    lv_obj_set_width(ui_Co2, LV_SIZE_CONTENT);   /// 26
    lv_obj_set_height(ui_Co2, LV_SIZE_CONTENT);    /// 10
    lv_obj_set_x(ui_Co2, 122);
    lv_obj_set_y(ui_Co2, 45);
    lv_obj_set_align(ui_Co2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Co2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Co2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Dust1 = lv_img_create(ui_iconWeather);
    lv_img_set_src(ui_Dust1, &ui_img_dust_png);
    lv_obj_set_width(ui_Dust1, LV_SIZE_CONTENT);   /// 30
    lv_obj_set_height(ui_Dust1, LV_SIZE_CONTENT);    /// 12
    lv_obj_set_x(ui_Dust1, -447);
    lv_obj_set_y(ui_Dust1, 145);
    lv_obj_set_align(ui_Dust1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dust1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Dust1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ChartTemp = lv_img_create(ui_iconWeather);
    lv_img_set_src(ui_ChartTemp, &ui_img_group_4_png);
    lv_obj_set_width(ui_ChartTemp, LV_SIZE_CONTENT);   /// 138
    lv_obj_set_height(ui_ChartTemp, LV_SIZE_CONTENT);    /// 89
    lv_obj_set_x(ui_ChartTemp, 169);
    lv_obj_set_y(ui_ChartTemp, -145);
    lv_obj_set_align(ui_ChartTemp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ChartTemp, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ChartTemp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ChartHumidity = lv_img_create(ui_iconWeather);
    lv_img_set_src(ui_ChartHumidity, &ui_img_group_4_png);
    lv_obj_set_width(ui_ChartHumidity, LV_SIZE_CONTENT);   /// 138
    lv_obj_set_height(ui_ChartHumidity, LV_SIZE_CONTENT);    /// 89
    lv_obj_set_x(ui_ChartHumidity, 330);
    lv_obj_set_y(ui_ChartHumidity, -146);
    lv_obj_set_align(ui_ChartHumidity, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ChartHumidity, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ChartHumidity, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_CO = lv_img_create(ui_iconWeather);
    lv_img_set_src(ui_CO, &ui_img_co_png);
    lv_obj_set_width(ui_CO, LV_SIZE_CONTENT);   /// 19
    lv_obj_set_height(ui_CO, LV_SIZE_CONTENT);    /// 10
    lv_obj_set_x(ui_CO, 326);
    lv_obj_set_y(ui_CO, 43);
    lv_obj_set_align(ui_CO, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CO, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_CO, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_IconCO = lv_img_create(ui_iconWeather);
    lv_img_set_src(ui_IconCO, &ui_img_1302822862);
    lv_obj_set_width(ui_IconCO, LV_SIZE_CONTENT);   /// 43
    lv_obj_set_height(ui_IconCO, LV_SIZE_CONTENT);    /// 43
    lv_obj_set_x(ui_IconCO, 329);
    lv_obj_set_y(ui_IconCO, -2);
    lv_obj_set_align(ui_IconCO, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_IconCO, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_IconCO, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image55 = lv_img_create(ui_iconWeather);
    lv_img_set_src(ui_Image55, &ui_img_frame_43_png);
    lv_obj_set_width(ui_Image55, LV_SIZE_CONTENT);   /// 118
    lv_obj_set_height(ui_Image55, LV_SIZE_CONTENT);    /// 127
    lv_obj_set_x(ui_Image55, 151);
    lv_obj_set_y(ui_Image55, 35);
    lv_obj_set_align(ui_Image55, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image55, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image55, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image74 = lv_img_create(ui_iconWeather);
    lv_img_set_src(ui_Image74, &ui_img_frame_43_png);
    lv_obj_set_width(ui_Image74, LV_SIZE_CONTENT);   /// 118
    lv_obj_set_height(ui_Image74, LV_SIZE_CONTENT);    /// 127
    lv_obj_set_x(ui_Image74, 153);
    lv_obj_set_y(ui_Image74, 206);
    lv_obj_set_align(ui_Image74, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image74, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image74, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image75 = lv_img_create(ui_iconWeather);
    lv_img_set_src(ui_Image75, &ui_img_frame_43_png);
    lv_obj_set_width(ui_Image75, LV_SIZE_CONTENT);   /// 118
    lv_obj_set_height(ui_Image75, LV_SIZE_CONTENT);    /// 127
    lv_obj_set_x(ui_Image75, 248);
    lv_obj_set_y(ui_Image75, 208);
    lv_obj_set_align(ui_Image75, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image75, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image75, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image76 = lv_img_create(ui_iconWeather);
    lv_img_set_src(ui_Image76, &ui_img_frame_43_png);
    lv_obj_set_width(ui_Image76, LV_SIZE_CONTENT);   /// 118
    lv_obj_set_height(ui_Image76, LV_SIZE_CONTENT);    /// 127
    lv_obj_set_x(ui_Image76, 352);
    lv_obj_set_y(ui_Image76, 209);
    lv_obj_set_align(ui_Image76, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image76, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image76, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image77 = lv_img_create(ui_iconWeather);
    lv_img_set_src(ui_Image77, &ui_img_frame_43_png);
    lv_obj_set_width(ui_Image77, LV_SIZE_CONTENT);   /// 118
    lv_obj_set_height(ui_Image77, LV_SIZE_CONTENT);    /// 127
    lv_obj_set_x(ui_Image77, 451);
    lv_obj_set_y(ui_Image77, 212);
    lv_obj_set_align(ui_Image77, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image77, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image77, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_IconPM25 = lv_img_create(ui_iconWeather);
    lv_img_set_src(ui_IconPM25, &ui_img_vector_png);
    lv_obj_set_width(ui_IconPM25, LV_SIZE_CONTENT);   /// 33
    lv_obj_set_height(ui_IconPM25, LV_SIZE_CONTENT);    /// 34
    lv_obj_set_x(ui_IconPM25, 226);
    lv_obj_set_y(ui_IconPM25, 1);
    lv_obj_set_align(ui_IconPM25, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_IconPM25, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_IconPM25, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image79 = lv_img_create(ui_iconWeather);
    lv_img_set_src(ui_Image79, &ui_img_1490288613);
    lv_obj_set_width(ui_Image79, LV_SIZE_CONTENT);   /// 71
    lv_obj_set_height(ui_Image79, LV_SIZE_CONTENT);    /// 71
    lv_obj_set_x(ui_Image79, 178);
    lv_obj_set_y(ui_Image79, -130);
    lv_obj_set_align(ui_Image79, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image79, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image79, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image80 = lv_img_create(ui_iconWeather);
    lv_img_set_src(ui_Image80, &ui_img_1490288613);
    lv_obj_set_width(ui_Image80, LV_SIZE_CONTENT);   /// 71
    lv_obj_set_height(ui_Image80, LV_SIZE_CONTENT);    /// 71
    lv_obj_set_x(ui_Image80, 338);
    lv_obj_set_y(ui_Image80, -131);
    lv_obj_set_align(ui_Image80, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image80, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image80, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_IconTemp = lv_img_create(ui_iconWeather);
    lv_img_set_src(ui_IconTemp, &ui_img_960377382);
    lv_obj_set_width(ui_IconTemp, LV_SIZE_CONTENT);   /// 14
    lv_obj_set_height(ui_IconTemp, LV_SIZE_CONTENT);    /// 14
    lv_obj_set_x(ui_IconTemp, 178);
    lv_obj_set_y(ui_IconTemp, -149);
    lv_obj_set_align(ui_IconTemp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_IconTemp, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_IconTemp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TVOCs = lv_img_create(ui_iconWeather);
    lv_img_set_src(ui_TVOCs, &ui_img_tvocs_png);
    lv_obj_set_width(ui_TVOCs, LV_SIZE_CONTENT);   /// 41
    lv_obj_set_height(ui_TVOCs, LV_SIZE_CONTENT);    /// 10
    lv_obj_set_x(ui_TVOCs, 427);
    lv_obj_set_y(ui_TVOCs, 42);
    lv_obj_set_align(ui_TVOCs, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TVOCs, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_TVOCs, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_IconHumidity = lv_img_create(ui_iconWeather);
    lv_img_set_src(ui_IconHumidity, &ui_img_1_png);
    lv_obj_set_width(ui_IconHumidity, LV_SIZE_CONTENT);   /// 10
    lv_obj_set_height(ui_IconHumidity, LV_SIZE_CONTENT);    /// 15
    lv_obj_set_x(ui_IconHumidity, 340);
    lv_obj_set_y(ui_IconHumidity, -150);
    lv_obj_set_align(ui_IconHumidity, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_IconHumidity, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_IconHumidity, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Humidity = lv_img_create(ui_iconWeather);
    lv_img_set_src(ui_Humidity, &ui_img_humidity_png);
    lv_obj_set_width(ui_Humidity, LV_SIZE_CONTENT);   /// 42
    lv_obj_set_height(ui_Humidity, LV_SIZE_CONTENT);    /// 10
    lv_obj_set_x(ui_Humidity, 339);
    lv_obj_set_y(ui_Humidity, -112);
    lv_obj_set_align(ui_Humidity, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Humidity, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Humidity, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_IconPM10 = lv_img_create(ui_iconWeather);
    lv_img_set_src(ui_IconPM10, &ui_img_vector_png);
    lv_obj_set_width(ui_IconPM10, LV_SIZE_CONTENT);   /// 33
    lv_obj_set_height(ui_IconPM10, LV_SIZE_CONTENT);    /// 34
    lv_obj_set_x(ui_IconPM10, 128);
    lv_obj_set_y(ui_IconPM10, 183);
    lv_obj_set_align(ui_IconPM10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_IconPM10, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_IconPM10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PM10 = lv_img_create(ui_iconWeather);
    lv_img_set_src(ui_PM10, &ui_img_pm10_png);
    lv_obj_set_width(ui_PM10, LV_SIZE_CONTENT);   /// 31
    lv_obj_set_height(ui_PM10, LV_SIZE_CONTENT);    /// 11
    lv_obj_set_x(ui_PM10, 125);
    lv_obj_set_y(ui_PM10, 223);
    lv_obj_set_align(ui_PM10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PM10, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_PM10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_CH4 = lv_img_create(ui_iconWeather);
    lv_img_set_src(ui_CH4, &ui_img_ch4_png);
    lv_obj_set_width(ui_CH4, LV_SIZE_CONTENT);   /// 26
    lv_obj_set_height(ui_CH4, LV_SIZE_CONTENT);    /// 10
    lv_obj_set_x(ui_CH4, 221);
    lv_obj_set_y(ui_CH4, 222);
    lv_obj_set_align(ui_CH4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CH4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_CH4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_IconCH4 = lv_img_create(ui_iconWeather);
    lv_img_set_src(ui_IconCH4, &ui_img_320661724);
    lv_obj_set_width(ui_IconCH4, LV_SIZE_CONTENT);   /// 46
    lv_obj_set_height(ui_IconCH4, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_x(ui_IconCH4, 224);
    lv_obj_set_y(ui_IconCH4, 183);
    lv_obj_set_align(ui_IconCH4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_IconCH4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_IconCH4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_NH3 = lv_img_create(ui_iconWeather);
    lv_img_set_src(ui_NH3, &ui_img_nh3_png);
    lv_obj_set_width(ui_NH3, LV_SIZE_CONTENT);   /// 26
    lv_obj_set_height(ui_NH3, LV_SIZE_CONTENT);    /// 10
    lv_obj_set_x(ui_NH3, 323);
    lv_obj_set_y(ui_NH3, 223);
    lv_obj_set_align(ui_NH3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_NH3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_NH3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_IconNH3 = lv_img_create(ui_iconWeather);
    lv_img_set_src(ui_IconNH3, &ui_img_777_png);
    lv_obj_set_width(ui_IconNH3, LV_SIZE_CONTENT);   /// 42
    lv_obj_set_height(ui_IconNH3, LV_SIZE_CONTENT);    /// 42
    lv_obj_set_x(ui_IconNH3, 329);
    lv_obj_set_y(ui_IconNH3, 182);
    lv_obj_set_align(ui_IconNH3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_IconNH3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_IconNH3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_IAQ = lv_img_create(ui_iconWeather);
    lv_img_set_src(ui_IAQ, &ui_img_iaq_png);
    lv_obj_set_width(ui_IAQ, LV_SIZE_CONTENT);   /// 21
    lv_obj_set_height(ui_IAQ, LV_SIZE_CONTENT);    /// 11
    lv_obj_set_x(ui_IAQ, 421);
    lv_obj_set_y(ui_IAQ, 222);
    lv_obj_set_align(ui_IAQ, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_IAQ, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_IAQ, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_IconTVOCs = lv_img_create(ui_iconWeather);
    lv_img_set_src(ui_IconTVOCs, &ui_img_66_png);
    lv_obj_set_width(ui_IconTVOCs, LV_SIZE_CONTENT);   /// 42
    lv_obj_set_height(ui_IconTVOCs, LV_SIZE_CONTENT);    /// 42
    lv_obj_set_x(ui_IconTVOCs, 423);
    lv_obj_set_y(ui_IconTVOCs, -3);
    lv_obj_set_align(ui_IconTVOCs, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_IconTVOCs, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_IconTVOCs, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PM25 = lv_img_create(ui_iconWeather);
    lv_img_set_src(ui_PM25, &ui_img_pm2_5_png);
    lv_obj_set_width(ui_PM25, LV_SIZE_CONTENT);   /// 37
    lv_obj_set_height(ui_PM25, LV_SIZE_CONTENT);    /// 11
    lv_obj_set_x(ui_PM25, 228);
    lv_obj_set_y(ui_PM25, 45);
    lv_obj_set_align(ui_PM25, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PM25, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_PM25, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_DvDust = lv_img_create(ui_iconWeather);
    lv_img_set_src(ui_DvDust, &ui_img_433014539);
    lv_obj_set_width(ui_DvDust, LV_SIZE_CONTENT);   /// 54
    lv_obj_set_height(ui_DvDust, LV_SIZE_CONTENT);    /// 15
    lv_obj_set_x(ui_DvDust, -272);
    lv_obj_set_y(ui_DvDust, 144);
    lv_obj_set_align(ui_DvDust, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DvDust, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_DvDust, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_IconIAQ = lv_img_create(ui_iconWeather);
    lv_img_set_src(ui_IconIAQ, &ui_img_194552828);
    lv_obj_set_width(ui_IconIAQ, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_IconIAQ, LV_SIZE_CONTENT);    /// 36
    lv_obj_set_x(ui_IconIAQ, 425);
    lv_obj_set_y(ui_IconIAQ, 181);
    lv_obj_set_align(ui_IconIAQ, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_IconIAQ, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_IconIAQ, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Temp = lv_img_create(ui_iconWeather);
    lv_img_set_src(ui_Temp, &ui_img_temp_png);
    lv_obj_set_width(ui_Temp, LV_SIZE_CONTENT);   /// 26
    lv_obj_set_height(ui_Temp, LV_SIZE_CONTENT);    /// 11
    lv_obj_set_x(ui_Temp, 177);
    lv_obj_set_y(ui_Temp, -112);
    lv_obj_set_align(ui_Temp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Temp, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Temp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_IconCO2 = lv_img_create(ui_iconWeather);
    lv_img_set_src(ui_IconCO2, &ui_img_2222_png);
    lv_obj_set_width(ui_IconCO2, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_IconCO2, LV_SIZE_CONTENT);    /// 41
    lv_obj_set_x(ui_IconCO2, 127);
    lv_obj_set_y(ui_IconCO2, 2);
    lv_obj_set_align(ui_IconCO2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_IconCO2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_IconCO2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Noise = lv_img_create(ui_iconWeather);
    lv_img_set_src(ui_Noise, &ui_img_44_png);
    lv_obj_set_width(ui_Noise, LV_SIZE_CONTENT);   /// 37
    lv_obj_set_height(ui_Noise, LV_SIZE_CONTENT);    /// 12
    lv_obj_set_x(ui_Noise, -174);
    lv_obj_set_y(ui_Noise, 143);
    lv_obj_set_align(ui_Noise, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Noise, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Noise, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_DvNoise = lv_img_create(ui_iconWeather);
    lv_img_set_src(ui_DvNoise, &ui_img_247956599);
    lv_obj_set_width(ui_DvNoise, LV_SIZE_CONTENT);   /// 31
    lv_obj_set_height(ui_DvNoise, LV_SIZE_CONTENT);    /// 15
    lv_obj_set_x(ui_DvNoise, 8);
    lv_obj_set_y(ui_DvNoise, 143);
    lv_obj_set_align(ui_DvNoise, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DvNoise, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_DvNoise, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Switch2 = lv_switch_create(ui_iconWeather);
    lv_obj_set_width(ui_Switch2, 45);
    lv_obj_set_height(ui_Switch2, 22);
    lv_obj_set_x(ui_Switch2, -265);
    lv_obj_set_y(ui_Switch2, 75);
    lv_obj_set_align(ui_Switch2, LV_ALIGN_CENTER);


    ui_Switch1 = lv_switch_create(ui_iconWeather);
    lv_obj_set_width(ui_Switch1, 45);
    lv_obj_set_height(ui_Switch1, 22);
    lv_obj_set_x(ui_Switch1, -401);
    lv_obj_set_y(ui_Switch1, 76);
    lv_obj_set_align(ui_Switch1, LV_ALIGN_CENTER);


    ui_Image3 = lv_img_create(ui_iconWeather);
    lv_img_set_src(ui_Image3, &ui_img_1902665014);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 28
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 29
    lv_obj_set_x(ui_Image3, -321);
    lv_obj_set_y(ui_Image3, -20);
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SmartLarm2 = lv_img_create(ui_iconWeather);
    lv_img_set_src(ui_SmartLarm2, &ui_img_1078347737);
    lv_obj_set_width(ui_SmartLarm2, LV_SIZE_CONTENT);   /// 42
    lv_obj_set_height(ui_SmartLarm2, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_SmartLarm2, -279);
    lv_obj_set_y(ui_SmartLarm2, -19);
    lv_obj_set_align(ui_SmartLarm2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SmartLarm2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SmartLarm2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Room2 = lv_img_create(ui_iconWeather);
    lv_img_set_src(ui_Room2, &ui_img_mr_water_png);
    lv_obj_set_width(ui_Room2, LV_SIZE_CONTENT);   /// 54
    lv_obj_set_height(ui_Room2, LV_SIZE_CONTENT);    /// 10
    lv_obj_set_x(ui_Room2, -280);
    lv_obj_set_y(ui_Room2, 20);
    lv_obj_set_align(ui_Room2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Room2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Room2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image6 = lv_img_create(ui_iconWeather);
    lv_img_set_src(ui_Image6, &ui_img_54_png);
    lv_obj_set_width(ui_Image6, LV_SIZE_CONTENT);   /// 91
    lv_obj_set_height(ui_Image6, LV_SIZE_CONTENT);    /// 71
    lv_obj_set_x(ui_Image6, -287);
    lv_obj_set_y(ui_Image6, 10);
    lv_obj_set_align(ui_Image6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image7 = lv_img_create(ui_iconWeather);
    lv_img_set_src(ui_Image7, &ui_img_54_png);
    lv_obj_set_width(ui_Image7, LV_SIZE_CONTENT);   /// 91
    lv_obj_set_height(ui_Image7, LV_SIZE_CONTENT);    /// 71
    lv_obj_set_x(ui_Image7, -414);
    lv_obj_set_y(ui_Image7, 10);
    lv_obj_set_align(ui_Image7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image7, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SmartLarm1 = lv_img_create(ui_iconWeather);
    lv_img_set_src(ui_SmartLarm1, &ui_img_1078347737);
    lv_obj_set_width(ui_SmartLarm1, LV_SIZE_CONTENT);   /// 42
    lv_obj_set_height(ui_SmartLarm1, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_SmartLarm1, -404);
    lv_obj_set_y(ui_SmartLarm1, -17);
    lv_obj_set_align(ui_SmartLarm1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SmartLarm1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SmartLarm1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Room1 = lv_img_create(ui_iconWeather);
    lv_img_set_src(ui_Room1, &ui_img_mr_water_png);
    lv_obj_set_width(ui_Room1, LV_SIZE_CONTENT);   /// 54
    lv_obj_set_height(ui_Room1, LV_SIZE_CONTENT);    /// 10
    lv_obj_set_x(ui_Room1, -408);
    lv_obj_set_y(ui_Room1, 21);
    lv_obj_set_align(ui_Room1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Room1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Room1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image10 = lv_img_create(ui_iconWeather);
    lv_img_set_src(ui_Image10, &ui_img_1902665014);
    lv_obj_set_width(ui_Image10, LV_SIZE_CONTENT);   /// 28
    lv_obj_set_height(ui_Image10, LV_SIZE_CONTENT);    /// 29
    lv_obj_set_x(ui_Image10, -451);
    lv_obj_set_y(ui_Image10, -19);
    lv_obj_set_align(ui_Image10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image10, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image13 = lv_img_create(ui_iconWeather);
    lv_img_set_src(ui_Image13, &ui_img_45_png);
    lv_obj_set_width(ui_Image13, LV_SIZE_CONTENT);   /// 153
    lv_obj_set_height(ui_Image13, LV_SIZE_CONTENT);    /// 31
    lv_obj_set_x(ui_Image13, 402);
    lv_obj_set_y(ui_Image13, -263);
    lv_obj_set_align(ui_Image13, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image13, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image14 = lv_img_create(ui_iconWeather);
    lv_img_set_src(ui_Image14, &ui_img_11_png);
    lv_obj_set_width(ui_Image14, LV_SIZE_CONTENT);   /// 133
    lv_obj_set_height(ui_Image14, LV_SIZE_CONTENT);    /// 27
    lv_obj_set_x(ui_Image14, 284);
    lv_obj_set_y(ui_Image14, -264);
    lv_obj_set_align(ui_Image14, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image14, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Delivery = lv_img_create(ui_iconWeather);
    lv_img_set_src(ui_Delivery, &ui_img_delivery_department_png);
    lv_obj_set_width(ui_Delivery, LV_SIZE_CONTENT);   /// 120
    lv_obj_set_height(ui_Delivery, LV_SIZE_CONTENT);    /// 13
    lv_obj_set_x(ui_Delivery, 411);
    lv_obj_set_y(ui_Delivery, -263);
    lv_obj_set_align(ui_Delivery, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Delivery, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Delivery, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AIoT = lv_img_create(ui_iconWeather);
    lv_img_set_src(ui_AIoT, &ui_img_aiot_department_png);
    lv_obj_set_width(ui_AIoT, LV_SIZE_CONTENT);   /// 99
    lv_obj_set_height(ui_AIoT, LV_SIZE_CONTENT);    /// 12
    lv_obj_set_x(ui_AIoT, 285);
    lv_obj_set_y(ui_AIoT, -263);
    lv_obj_set_align(ui_AIoT, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AIoT, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_AIoT, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_NumCo2 = lv_label_create(ui_iconWeather);
    lv_obj_set_width(ui_NumCo2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NumCo2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NumCo2, 127);
    lv_obj_set_y(ui_NumCo2, 75);
    lv_obj_set_align(ui_NumCo2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_NumCo2, "500.45");
    lv_obj_set_style_text_color(ui_NumCo2, lv_color_hex(0xFBFBFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_NumCo2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_NumCo2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_NumCo2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_NumCo2, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_NumCo2, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_NumCo2, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NumPM25 = lv_label_create(ui_iconWeather);
    lv_obj_set_width(ui_NumPM25, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NumPM25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NumPM25, 225);
    lv_obj_set_y(ui_NumPM25, 85);
    lv_obj_set_align(ui_NumPM25, LV_ALIGN_CENTER);
    lv_label_set_text(ui_NumPM25, "12.00\n");
    lv_obj_set_style_text_color(ui_NumPM25, lv_color_hex(0xFBFBFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_NumPM25, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_NumPM25, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_NumPM25, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_NumPM25, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_NumPM25, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_NumPM25, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NumCO = lv_label_create(ui_iconWeather);
    lv_obj_set_width(ui_NumCO, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NumCO, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NumCO, 330);
    lv_obj_set_y(ui_NumCO, 76);
    lv_obj_set_align(ui_NumCO, LV_ALIGN_CENTER);
    lv_label_set_text(ui_NumCO, "8.30");
    lv_obj_set_style_text_color(ui_NumCO, lv_color_hex(0xFBFBFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_NumCO, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_NumCO, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_NumCO, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_NumCO, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_NumCO, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_NumCO, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NumTVOCs = lv_label_create(ui_iconWeather);
    lv_obj_set_width(ui_NumTVOCs, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NumTVOCs, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NumTVOCs, 428);
    lv_obj_set_y(ui_NumTVOCs, 78);
    lv_obj_set_align(ui_NumTVOCs, LV_ALIGN_CENTER);
    lv_label_set_text(ui_NumTVOCs, "90.55");
    lv_obj_set_style_text_color(ui_NumTVOCs, lv_color_hex(0xFBFBFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_NumTVOCs, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NumPM10 = lv_label_create(ui_iconWeather);
    lv_obj_set_width(ui_NumPM10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NumPM10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NumPM10, 127);
    lv_obj_set_y(ui_NumPM10, 252);
    lv_obj_set_align(ui_NumPM10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_NumPM10, "12.00");
    lv_obj_set_style_text_color(ui_NumPM10, lv_color_hex(0xFBFBFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_NumPM10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_NumPM10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_NumPM10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_NumPM10, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_NumPM10, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_NumPM10, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NumCH4 = lv_label_create(ui_iconWeather);
    lv_obj_set_width(ui_NumCH4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NumCH4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NumCH4, 223);
    lv_obj_set_y(ui_NumCH4, 252);
    lv_obj_set_align(ui_NumCH4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_NumCH4, "15.00");
    lv_obj_set_style_text_color(ui_NumCH4, lv_color_hex(0xFBFBFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_NumCH4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_NumCH4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_NumCH4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_NumCH4, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_NumCH4, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_NumCH4, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NumNH3 = lv_label_create(ui_iconWeather);
    lv_obj_set_width(ui_NumNH3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NumNH3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NumNH3, 327);
    lv_obj_set_y(ui_NumNH3, 253);
    lv_obj_set_align(ui_NumNH3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_NumNH3, "30.74");
    lv_obj_set_style_text_color(ui_NumNH3, lv_color_hex(0xFBFBFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_NumNH3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_NumNH3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_NumNH3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_NumNH3, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_NumNH3, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_NumNH3, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    // ui_NumIAQ = lv_label_create(ui_iconWeather);
    // lv_obj_set_width(ui_NumIAQ, LV_SIZE_CONTENT);   /// 1
    // lv_obj_set_height(ui_NumIAQ, LV_SIZE_CONTENT);    /// 1
    // lv_obj_set_x(ui_NumIAQ, 430);
    // lv_obj_set_y(ui_NumIAQ, 253);
    // lv_obj_set_align(ui_NumIAQ, LV_ALIGN_CENTER);
    // lv_label_set_text(ui_NumIAQ, "38");
    // lv_obj_set_style_text_color(ui_NumIAQ, lv_color_hex(0xFBFBFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_text_opa(ui_NumIAQ, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_text_letter_space(ui_NumIAQ, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_text_line_space(ui_NumIAQ, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_text_align(ui_NumIAQ, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_text_decor(ui_NumIAQ, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_text_font(ui_NumIAQ, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NumAQI = lv_label_create(ui_iconWeather);
    lv_obj_set_width(ui_NumAQI, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NumAQI, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NumAQI, -80);
    lv_obj_set_y(ui_NumAQI, -55);
    lv_obj_set_align(ui_NumAQI, LV_ALIGN_CENTER);
    //lv_label_set_text(ui_NumAQI, "42.00");
    lv_obj_set_style_text_color(ui_NumAQI, lv_color_hex(0xFBFBFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_NumAQI, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_NumAQI, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_NumAQI, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_NumAQI, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_NumAQI, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_NumAQI, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_border_color(ui_NumAQI, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_border_opa(ui_NumAQI, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_border_width(ui_NumAQI, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_border_side(ui_NumAQI, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NumTemp = lv_label_create(ui_iconWeather);
    lv_obj_set_width(ui_NumTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NumTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NumTemp, 179);
    lv_obj_set_y(ui_NumTemp, -131);
    lv_obj_set_align(ui_NumTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_NumTemp, "25°C");
    lv_obj_set_style_text_color(ui_NumTemp, lv_color_hex(0xFBFBFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_NumTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_NumTemp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_NumTemp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_NumTemp, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_NumTemp, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_NumTemp, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NumHumdity = lv_label_create(ui_iconWeather);
    lv_obj_set_width(ui_NumHumdity, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NumHumdity, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NumHumdity, 339);
    lv_obj_set_y(ui_NumHumdity, -131);
    lv_obj_set_align(ui_NumHumdity, LV_ALIGN_CENTER);
    //lv_label_set_text(ui_NumHumdity, "");
    lv_obj_set_style_text_color(ui_NumHumdity, lv_color_hex(0xFBFBFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_NumHumdity, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_NumHumdity, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_NumHumdity, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_NumHumdity, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_NumHumdity, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_NumHumdity, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    // ui_Num = lv_label_create(ui_iconWeather);
    // lv_obj_set_width(ui_Num, LV_SIZE_CONTENT);   /// 1
    // lv_obj_set_height(ui_Num, LV_SIZE_CONTENT);    /// 1
    // lv_obj_set_x(ui_Num, -430);
    // lv_obj_set_y(ui_Num, -104);
    // lv_obj_set_align(ui_Num, LV_ALIGN_CENTER);
    // lv_label_set_text(ui_Num, "25°C");
    // lv_obj_set_style_text_color(ui_Num, lv_color_hex(0xFBFBFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_text_opa(ui_Num, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_text_letter_space(ui_Num, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_text_line_space(ui_Num, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_text_align(ui_Num, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_text_decor(ui_Num, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_text_font(ui_Num, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

}
